// <auto-generated />
namespace Trash_Collector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakingDateTimePropertiesNullabletoseeifthatstopserror : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingDateTimePropertiesNullabletoseeifthatstopserror));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291235193_Making DateTime Properties Nullable to see if that stops error"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
